# Generated by Django 4.1 on 2024-12-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_products_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="color",
        ),
    ]
