# Generated by Django 4.1 on 2024-12-25 17:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_products_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
