# Generated by Django 4.1 on 2024-12-26 14:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_products_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
